site_name: Dev How To

theme:
  name: material
  palette:
    accent: indigo
  custom_dir: overrides
  features:
    - content.code.annotate
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.indexes

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - meta
  - attr_list
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - toc:
      permalink: ''
      baselevel: 1
      separator: '-'
  - admonition
  - plantuml_markdown:
      server: http://www.plantuml.com/plantuml

extra:
  generator: false
  social:
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.com/fernandobasso


######################################################################
######################## Site navigation and pages ###################
######################################################################

nav:
  - Home: index.md

  - Command Line and Shell Scripting:
    - Shell Redirection: shell/shell-redirection.md
    - tar: shell/tar.md
    - unzip: shell/unzip.md
    - grep: shell/grep.md
    - Useful SSH Commands: shell/ssh-useful-commands.md

    - Git:
      - Git Add: shell/git/git-add.md

  - Programming Languages:

    - TypeScript:
      - programming-languages/typescript/index.md
      - Functions: programming-languages/typescript/functions.md
      - Ted Navard Advanced TypeScript (video notes):
        - Intro: programming-languages/typescript/ted-neward-advanced-typescript/00-intro.md
        - Type Compatibility: programming-languages/typescript/ted-neward-advanced-typescript/01-type-compatibility.md
        - Simple and Compound Types: programming-languages/typescript/ted-neward-advanced-typescript/02-simple-compound-types.md
        - Decorators: programming-languages/typescript/ted-neward-advanced-typescript/03-decorators.md
        - Symbols: programming-languages/typescript/ted-neward-advanced-typescript/04-symbols.md
        - Iterators: programming-languages/typescript/ted-neward-advanced-typescript/05-iterators.md
        - Generators: programming-languages/typescript/ted-neward-advanced-typescript/06-generators.md
        - Generics: programming-languages/typescript/ted-neward-advanced-typescript/07-generics.md

      - Quizzes:
        - programming-languages/typescript/quizzes/index.md
        - Basic Types: programming-languages/typescript/quizzes/basic-types.md
        - Composite Types: programming-languages/typescript/quizzes/composite-types.md
        - Type Assertions: programming-languages/typescript/quizzes/type-assertions.md
        - Functions: programming-languages/typescript/quizzes/functions.md

  - Functional Programming:
    - PureScript:
      - Intro: functional-programming/purescript/intro.md
      - REPL: functional-programming/purescript/repl.md
      - Types:
        - functional-programming/purescript/types/index.md
        - Data Types: functional-programming/purescript/types/data-types.md
      - Number Types: functional-programming/purescript/number-types.md
      - Char and String Types: functional-programming/purescript/char-string-types.md
      - Functions: functional-programming/purescript/functions.md

  - Algorithms and Data Structures:

    - Exercism:
      - Intro: algorithms-data-structures/exercism/index.md

      - TypeScript:
        - Two-Fer: algorithms-data-structures/exercism/typescript/two-fer.md
        - Resistor Color Duo: algorithms-data-structures/exercism/typescript/resistor-color-duo.md
        - Resistor Color Trio: algorithms-data-structures/exercism/typescript/resistor-color-trio.md

  - Misc:
    - Text Editors:
      - Vim:
        - Vim Useful Tips: misc/text-editors/vim/useful-tips.md
        - Vim Gotchas: misc/text-editors/vim/gotchas.md

    - Linux:
      - Xfce Power User Tips: misc/linux/xfce-power-tips.md

    - PlantUML Diagrams:
      - Sequence Diagrams: misc/plantuml-diagrams/sequence.md
